language: python
python:
  - 2.7
install:
  - easy_install --version
  - pip install setuptools==18.3.2
  - mkdir -p buildout-cache/{eggs,downloads}
  - bin/pip install zc.buildout
  - bin/buildout -Nc travis.cfg
script:
  - bin/test
after_success:
  - bin/createcoverage
  - pip install coveralls==0.5
  - coveralls

notifications:
  email:
    - devs@imio.be
